# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ixvDdPnF5RsGGzQJWG8z9irldzP-HHeR
"""

!pip install scikit-learn

from google.colab import drive
drive.mount('/content/drive')

DATA_DIR = "/content/drive/MyDrive/mtllm/data"  # adjust path
CODE_DIR = "/content/drive/MyDrive/mtllm/code"            # where validation.py lives

import sys
sys.path.append(CODE_DIR)

import os, glob, random
import validation  # this is validation.py
from validation import Article, validate_articles, check_citations

from sklearn.feature_extraction.text import TfidfVectorizer

# 2.1 Load a subset of raw texts to fit the vectorizer
def collect_corpus_texts(data_dir, limit=5000):
    texts = []
    for i, path in enumerate(glob.glob(os.path.join(data_dir, "*.txt"))):
        if i >= limit:
            break
        with open(path, encoding="utf-8", errors="ignore") as f:
            texts.append(f.read())
    return texts

corpus_texts = collect_corpus_texts(DATA_DIR, limit=5000)

vectorizer = TfidfVectorizer(max_features=2000)
vectorizer.fit(corpus_texts)

# 2.2 Monkey-patch embed_text inside the validation module
import numpy as np

def embed_text(text: str) -> np.ndarray:
    return vectorizer.transform([text]).toarray()[0]

validation.embed_text = embed_text

def load_articles_from_dir(data_dir, limit=5000):
    articles = []
    paths = glob.glob(os.path.join(data_dir, "*.txt"))
    random.shuffle(paths)  # random subset

    for i, path in enumerate(paths):
        if i >= limit:
            break
        with open(path, encoding="utf-8", errors="ignore") as f:
            txt = f.read()

        lines = txt.strip().splitlines()
        title = lines[0].strip() if lines else os.path.basename(path)
        abstract = " ".join(lines[1:10])  # first few lines as pseudo-abstract

        pmcid = os.path.splitext(os.path.basename(path))[0]

        art = Article(
            pmcid=pmcid,
            doi=None,
            title=title[:200],
            abstract=abstract[:3000],
            journal="SampleCorpus",
            year=2020,
            citation_count=0,
            is_peer_reviewed=False,
            is_retracted=False,
        )
        articles.append(art)

    return articles

articles = load_articles_from_dir(DATA_DIR, limit=3000)
len(articles)

query = "antibiotic resistance in gram-negative bacteria"

validated = validate_articles(query, articles)
len(validated), len(articles)

import matplotlib.pyplot as plt

scores = [a.validation_score for a in validated]

plt.figure()
plt.hist(scores, bins=20)
plt.xlabel("Validation Score")
plt.ylabel("Frequency")
plt.title("Distribution of Article Validation Scores (Real Data)")
plt.show()

top5 = sorted(validated, key=lambda a: a.validation_score, reverse=True)[:5]
for a in top5:
    print(a.pmcid, a.validation_score, a.title)
    print()

# Use top 3 validated articles as "cited" papers
top3 = sorted(validated, key=lambda a: a.validation_score, reverse=True)[:3]

answer_body = f"""
Several studies have investigated this problem [1, 2]. Recent work emphasizes the
role of mobile genetic elements [3].
"""

# We'll pretend these are the reference list entries:
ref_lines = []
for i, art in enumerate(top3, start=1):
    ref_lines.append(f"[{i}] {art.title}. SampleCorpus, 2020. PMCID {art.pmcid}.")
ref_text = "\n".join(ref_lines)

print(ref_text)

# Sort scores and take the top 50
sorted_scores = np.sort(scores)
top_k = sorted_scores[-50:]

plt.figure(figsize=(8, 5))
plt.plot(range(1, len(top_k) + 1), top_k, marker="o")
plt.xlabel("Rank (1 = highest)")
plt.ylabel("Validation score")
plt.title("Top 50 Article Validation Scores")
plt.tight_layout()

plt.savefig("/content/drive/MyDrive/mtllm/validation_top50.png", dpi=300, bbox_inches="tight")
plt.show()

# Define your own bands (you can tweak these)
import numpy as np

scores = np.array(scores)
low_mask = scores < 0.20
mid_mask = (scores >= 0.20) & (scores < 0.28)
high_mask = scores >= 0.28

counts = [low_mask.sum(), mid_mask.sum(), high_mask.sum()]
labels = ["Low", "Medium", "High"]

plt.figure(figsize=(6, 4))
plt.bar(labels, counts)
plt.xlabel("Confidence band")
plt.ylabel("Number of articles")
plt.title("Articles per Validation Band")
plt.tight_layout()

plt.savefig("/content/drive/MyDrive/mtllm/validation_bands.png", dpi=300, bbox_inches="tight")
plt.show()

counts